name: Deploy to Azure Blob Storage and Purge CDN

on:
  push:
    branches:
      - main # Or your main branch name
  workflow_dispatch: # Allow manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build
        env:
          # --- Secrets ---
          DISCORD_CLIENT_SECRET: ${{ secrets.DISCORD_CLIENT_SECRET }}

          # --- Variables ---
          DISCORD_CLIENT_ID: ${{ vars.DISCORD_CLIENT_ID }}
          DISCORD_REDIRECT_URI: ${{ vars.DISCORD_REDIRECT_URI }}
          PUBLIC_VERSION: ${{ vars.PUBLIC_VERSION }}
          PUBLIC_DISCORD_CLIENT_ID: ${{ vars.PUBLIC_DISCORD_CLIENT_ID }}
          PUBLIC_DISCORD_REDIRECT_URI: ${{ vars.PUBLIC_DISCORD_REDIRECT_URI }}
          PUBLIC_USER_TABLE_FUNCTION_URL: ${{ vars.PUBLIC_USER_TABLE_FUNCTION_URL }}
          PUBLIC_ADD_TO_SEEKING_FUNCTION_URL: ${{ vars.PUBLIC_ADD_TO_SEEKING_FUNCTION_URL }}
          PUBLIC_GET_SEEKING_LIST_FUNCTION_URL: ${{ vars.PUBLIC_GET_SEEKING_LIST_FUNCTION_URL }}
          PUBLIC_DELETE_FROM_SEEKING_FUNCTION_URL: ${{ vars.PUBLIC_DELETE_FROM_SEEKING_FUNCTION_URL }}
          PUBLIC_DELETE_USER_ACCOUNT_FUNCTION_URL: ${{ vars.PUBLIC_DELETE_USER_ACCOUNT_FUNCTION_URL }}
          PUBLIC_GET_USER_TABLES_FUNCTION_URL: ${{ vars.PUBLIC_GET_USER_TABLES_FUNCTION_URL }}
          PUBLIC_GET_SYSTEM_STATUS_FUNCTION_URL: ${{ vars.PUBLIC_GET_SYSTEM_STATUS_FUNCTION_URL }}
          PUBLIC_AUTH_ENDPOINT: ${{ vars.PUBLIC_AUTH_ENDPOINT }}
          PUBLIC_LOGIN_ENDPOINT: ${{ vars.PUBLIC_LOGIN_ENDPOINT }}
          PUBLIC_LOGOUT_ENDPOINT: ${{ vars.PUBLIC_LOGOUT_ENDPOINT }}
        run: npm run build

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
  
      - name: Sync to Azure Blob Storage
        uses: Azure/CLI@v1
        with:
          inlineScript: |
            # Parse credentials from the Azure Login secret JSON
            # Requires jq (installed in the previous step)
            AZURE_CREDENTIALS_JSON='${{ secrets.AZURE_CREDENTIALS }}'
            AZCOPY_SPA_CLIENT_ID=$(echo "$AZURE_CREDENTIALS_JSON" | jq -r .clientId)
            AZCOPY_SPA_CLIENT_SECRET=$(echo "$AZURE_CREDENTIALS_JSON" | jq -r .clientSecret)
            AZCOPY_TENANT_ID=$(echo "$AZURE_CREDENTIALS_JSON" | jq -r .tenantId)
  
            if [ -z "$AZCOPY_SPA_CLIENT_ID" ] || [ -z "$AZCOPY_SPA_CLIENT_SECRET" ] || [ -z "$AZCOPY_TENANT_ID" ]; then
              echo "Error: Failed to parse AZURE_CREDENTIALS for AzCopy environment variables."
              exit 1
            fi
  
            export AZCOPY_AUTO_LOGIN_TYPE="SPN"
            export AZCOPY_SPA_CLIENT_ID
            export AZCOPY_SPA_CLIENT_SECRET
            export AZCOPY_TENANT_ID
  
            echo "AzCopy SPN environment variables set. AZCOPY_SPA_CLIENT_ID: $AZCOPY_SPA_CLIENT_ID" 
  
            # Get Storage Account Name
            ACCOUNT_NAME="${{ secrets.STORAGE_ACCOUNT_NAME || vars.STORAGE_ACCOUNT_NAME }}"
            if [ -z "$ACCOUNT_NAME" ]; then
              echo "Error: STORAGE_ACCOUNT_NAME secret or variable not set."
              exit 1
            fi
  
            echo "Syncing to Storage Account: $ACCOUNT_NAME, Container: \$web"
  
            az storage blob sync \
              --account-name "$ACCOUNT_NAME" \
              --container-name '$web' \
              --auth-mode login \
              --source build/ \
              --delete-destination true
  
            echo "Sync command completed."

      - name: Purge CDN endpoint
        uses: Azure/CLI@v1
        with:
          inlineScript: |
            CDN_PROFILE="${{ vars.CDN_PROFILE_NAME || 'seeker-cityoftraitors-com-cdn-1' }}"
            CDN_ENDPOINT="${{ vars.CDN_ENDPOINT_NAME || 'seeker-cityoftraitors-com-cdn-1' }}"
            RESOURCE_GROUP="${{ vars.RESOURCE_GROUP_NAME || 'seeker-rg' }}"
            echo "Purging CDN Endpoint: $CDN_ENDPOINT in profile $CDN_PROFILE"
            az cdn endpoint purge --content-paths "/*" --profile-name "$CDN_PROFILE" --name "$CDN_ENDPOINT" --resource-group "$RESOURCE_GROUP"

      - name: Azure Logout
        if: always()
        run: az logout
