name: Deploy to Azure Blob Storage and Purge CDN

on:
  push:
    branches:
      - main
  workflow_dispatch: 
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build
        env:
          # --- Secrets ---
          DISCORD_CLIENT_SECRET: ${{ secrets.DISCORD_CLIENT_SECRET }}

          # --- Variables ---
          DISCORD_CLIENT_ID: ${{ vars.DISCORD_CLIENT_ID }}
          DISCORD_REDIRECT_URI: ${{ vars.DISCORD_REDIRECT_URI }}
          PUBLIC_VERSION: ${{ vars.PUBLIC_VERSION }}
          PUBLIC_DISCORD_CLIENT_ID: ${{ vars.PUBLIC_DISCORD_CLIENT_ID }}
          PUBLIC_DISCORD_REDIRECT_URI: ${{ vars.PUBLIC_DISCORD_REDIRECT_URI }}
          PUBLIC_USER_TABLE_FUNCTION_URL: ${{ vars.PUBLIC_USER_TABLE_FUNCTION_URL }}
          PUBLIC_ADD_TO_SEEKING_FUNCTION_URL: ${{ vars.PUBLIC_ADD_TO_SEEKING_FUNCTION_URL }}
          PUBLIC_GET_SEEKING_LIST_FUNCTION_URL: ${{ vars.PUBLIC_GET_SEEKING_LIST_FUNCTION_URL }}
          PUBLIC_DELETE_FROM_SEEKING_FUNCTION_URL: ${{ vars.PUBLIC_DELETE_FROM_SEEKING_FUNCTION_URL }}
          PUBLIC_DELETE_USER_ACCOUNT_FUNCTION_URL: ${{ vars.PUBLIC_DELETE_USER_ACCOUNT_FUNCTION_URL }}
          PUBLIC_GET_USER_TABLES_FUNCTION_URL: ${{ vars.PUBLIC_GET_USER_TABLES_FUNCTION_URL }}
          PUBLIC_GET_SYSTEM_STATUS_FUNCTION_URL: ${{ vars.PUBLIC_GET_SYSTEM_STATUS_FUNCTION_URL }}
          PUBLIC_AUTH_ENDPOINT: ${{ vars.PUBLIC_AUTH_ENDPOINT }}
          PUBLIC_LOGIN_ENDPOINT: ${{ vars.PUBLIC_LOGIN_ENDPOINT }}
          PUBLIC_LOGOUT_ENDPOINT: ${{ vars.PUBLIC_LOGOUT_ENDPOINT }}
          # --- Add missing VITE variables needed by auth.ts ---
          VITE_LOGIN_URL: ${{ vars.VITE_LOGIN_URL }}
          VITE_USER_INFO_URL: ${{ vars.VITE_USER_INFO_URL }}
        run: npm run build

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Clean existing blobs
        uses: azure/CLI@v1
        with:
          inlineScript: |
            ACCOUNT_NAME="${{ secrets.STORAGE_ACCOUNT_NAME || vars.STORAGE_ACCOUNT_NAME }}"
            ACCOUNT_KEY=$(az storage account keys list --account-name "$ACCOUNT_NAME" --query '[0].value' -o tsv)
            
            echo "Cleaning existing files in $web container"
            az storage blob delete-batch \
              --account-name "$ACCOUNT_NAME" \
              --account-key "$ACCOUNT_KEY" \
              --source '$web'
  
      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            # Get storage account name
            ACCOUNT_NAME="${{ secrets.STORAGE_ACCOUNT_NAME || vars.STORAGE_ACCOUNT_NAME }}"
            
            # Get the storage account key
            ACCOUNT_KEY=$(az storage account keys list --account-name "$ACCOUNT_NAME" --query '[0].value' -o tsv)
            
            # Use az storage blob upload-batch with the storage key
            az storage blob upload-batch \
              --account-name "$ACCOUNT_NAME" \
              --account-key "$ACCOUNT_KEY" \
              --destination '$web' \
              --source ./build \
              --overwrite true

      - name: Purge CDN endpoint
        uses: Azure/CLI@v1
        with:
          inlineScript: |
            CDN_PROFILE="${{ vars.CDN_PROFILE_NAME || 'seeker-cityoftraitors-com-cdn-1' }}"
            CDN_ENDPOINT="${{ vars.CDN_ENDPOINT_NAME || 'seeker-cityoftraitors-com-cdn-1' }}"
            RESOURCE_GROUP="${{ vars.RESOURCE_GROUP_NAME || 'seeker-rg' }}"
            echo "Purging CDN Endpoint: $CDN_ENDPOINT in profile $CDN_PROFILE"
            az cdn endpoint purge --content-paths "/*" --profile-name "$CDN_PROFILE" --name "$CDN_ENDPOINT" --resource-group "$RESOURCE_GROUP"

      - name: Azure Logout
        if: always()
        run: az logout
